url: https://api-v2-prisma.pabau.com/graphql
headers: 
  authorization: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJyZW1vdGVfdXJsIjoiaHR0cHM6Ly9uZXctY2xpbmljLnBhYmF1Lm1lIiwicmVtb3RlX2Nvbm5lY3QiOiJodHRwczovL2Nvbm5lY3QtbmV3LWNsaW5pYy5wYWJhdS5tZSIsInVzZXIiOjgzOTQ0LCJjb21wYW55Ijo4MTE5LCJhZG1pbiI6dHJ1ZSwib3duZXIiOmZhbHNlLCJsYW5ndWFnZSI6eyJ1c2VyIjoiRU4tR0IiLCJjb21wYW55IjoiZW4ifSwiaHR0cHM6Ly9oYXN1cmEuaW8vand0L2NsYWltcyI6eyJ4LWhhc3VyYS1hbGxvd2VkLXJvbGVzIjpbInB1YmxpYyIsInVzZXIiXSwieC1oYXN1cmEtZGVmYXVsdC1yb2xlIjoidXNlciIsIngtaGFzdXJhLXVzZXItaWQiOiI4Mzk0NCIsIngtaGFzdXJhLW9yZy1pZCI6IjgxMTkiLCJ4LWhhc3VyYS1wYWJhdSI6InRlc3QifSwiaWF0IjoxNjI2NTEwNjY0fQ.NK9OzxgBxmOnCiMIlJAd_MbPKSpoO2jgKYN7kS5HcW_q4_W9frx7opJ4TL_jTps52bGA__zURqsFkXgt0Bq_gA
  queries:
  - name: ContactsPaginated
    tools: [autocannon]
    execution_strategy: REQUESTS_PER_SECOND
    rps: 200
    duration: 10s
    connections: 50
    query: |
      query ContactsPaginated {
        findManyCmContact(take: 200) {
          ID
          Avatar
          OwnerID
        }
      }
  - name: ExpensiveQueryIncrementalLoadTest
    tools: [autocannon]
    execution_strategy: MAX_REQUESTS_IN_DURATION
    duration: 5s
    query: |
      query UsersWithSearchAndNestedModels {
        findManyUser(where: {
          username: {
            not: {
              contains: "@deletecd"
            }
          }
        }) {
          id
          full_name
          Booking(take: 50) {
            id
            UID
            title
          }
          InvProduct {
            code
            id
            unit
          }
        }
      }

  - name: ExpensiveMutationFixedRequestsTest
    tools: [autocannon]
    execution_strategy: FIXED_REQUEST_NUMBER
    requests: 4000
    query: |
      mutation Login{
        login(username: "new@crm.pabau.com", password: "Toshe@1234")
      }